name: labbd-trabalho3

services:
  db:
    image: postgres:latest
    container_name: labbd-trabalho3
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./:/app
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: formula1fia
      POSTGRES_USER: fia
      POSTGRES_PASSWORD: fia123

volumes:
  pgdata: